site_name: Test docs
site_description: "A docs test"
site_author: "Patrician Team"
docs_dir: docs/
repo_name: "patricianapp/docs"
repo_url: "https://github.com/patricianapp/docs"
nav:
  - Home: index.md
theme:
  name: "material"
