site_name: Patrician Docs
site_description: "A webpage for your music collection"
site_author: "Patrician Team"
docs_dir: docs/
repo_name: "patricianapp/docs"
repo_url: "https://github.com/patricianapp/docs"
nav:
  - Home: index.md
theme:
  name: "material"
